### ISSUE TITLE
CLI usage on Windows results in Error: spawn C:\...\electron-har\src\..\bin\electron-har ENOENT

### ISSUE THREAD

**Issue by bmcminn** [shyiko/electron-har#3]
Not sure what's going on here... That file exists, and I can run the binary directly in my CLI per the README.md examples, though pragmatic access causes an ENOENT error when spawning the bin file.

Anyone else run into this?

**Comment by shyiko** [comment]
Hi. Yeah, it's due to https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows (https://github.com/shyiko/electron-har/blob/master/src/index.js#L33). If you have some spare time - I would be happy to merge in a PR. If not - I'll fix it myself. Let me know how you want to proceed. In any case, thank you for the bug report!

**Comment by bmcminn** [comment]
Digging into it, I did realize that the `bin` files are not executables under Windows.

Modifying the `src/index.js` file, I think we can make a context switch in `execFile()` to append `.cmd` based on `if os.platform() === "win32"`.

Should be a quick fix to test and issue a PR for, but if you have other ideas around this, by all means.

**Comment by shyiko** [comment]
That's one way to do it. I think https://github.com/kevva/cross-exec-file should be easier though. Pick whichever you like :)
